config/routes.rb
Rails.application.routes.draw do
  root to: "links#index"
  get "/login", to: "sessions#new"
  get "/sign_up", to: "users#new"
  resources :users, only: [:new, :create]
  resources :links, only: [:index, :create, :show, :edit, :update]
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :links, only: [:update]
    end
  end
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :user
  validate :must_have_valid_url

  private

  def must_have_valid_url
    errors.add(:url, "is not valid") unless valid_url?
  end

  def valid_url?
    uri = URI.parse(url)
    uri.kind_of?(URI::HTTP)
  rescue URI::InvalidURIError
    false
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :links
  validates :email, uniqueness: true
end

app/controllers/api/api_controller.rb
class Api::ApiController < ApplicationController
  protect_from_forgery with: :null_session
end

app/controllers/api/v1/links_controller.rb
class Api::V1::LinksController < Api::ApiController
  respond_to :json

  def update
    respond_with Link.find(params[:id]).update_attributes(link_params)
  end

  private

  def link_params
    params.require(:link).permit(:read)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def check_current_user
    redirect_to login_path unless current_user
  end
end

app/controllers/links_controller.rb
require 'uri'

class LinksController < ApplicationController
  before_action :check_current_user

  def index
    @link ||= Link.new
    @links = current_user.links
  end

  def create
    @link = current_user.links.new(link_params)
    if @link.save
      redirect_to link_path(@link)
    else
      @links = current_user.links
      render :index
    end
  end

  def edit
    @link = current_user.links.find_by(id: params[:id])
  end

  def update
    @link = current_user.links.find_by(id: params[:id])

    if @link.update_attributes(link_params)
      redirect_to links_path
    else
      render :edit
    end
  end

  def show
    @link = current_user.links.find_by(id: params[:id])
  end

  private

  def link_params
    params.require(:link).permit(:title, :url, :read)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])

    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to links_path
    else
      flash[:error] = "Invalid login credentials. Nice Try Meeka and Steve."
      redirect_to login_path
    end
  end

  def destroy
    session.clear
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to links_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ThoughtBox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/links/_form.html.erb
<%= form_for @link do |f| %>
  <%= render partial: "shared/errors", locals: { target: @link } %>

  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <br>
    <%= f.label :url %>
    <%= f.text_field :url, required: true %>
    <br>
    <%= f.submit yield(:button_text) %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h2>Edit Link</h2>
<% provide(:button_text, "Update Link") %>
<%= render partial: "form" %>

app/views/links/index.html.erb
<%= link_to "Sign Out", logout_path %>
<% provide(:button_text, "Create New Link") %>
<div class="new-link">
  <h2>Create New Link</h2>
  <br><br>
  <%= render partial: "form" %>
</div>
<br>
<div class="search-box">
  <%= form_tag('#') do %>
    <%= label_tag(:search) %>
    <%= text_field_tag(:search) %>
  <% end %>
</div>
<br>
<button class="filter-by-unread">
  Filter by Unread
</button>
<button class="filter-by-read">
  Filter by Read
</button>
<button class="show-all">
  Show All
</button>
<button class="sort-alphabetically">
  Sort Alphabetically
</button>

<div class="links">
  <ul>


  <% @links.each do |link| %>
    <% if link.valid? %>
    <li>
      <div id="link-<%= link.id %>" class="link <%= link.read ? "read-link": "unread-link link-#{link.id}"%>">
        <div class="title">
          Title: <%= link.title %>
        </div>
        <div class="url">
          URL: <%= link.url %>
        </div>
        <div class="read-status" data-id="<%= link.id %>">
          Read: <%= link.read %>
        </div>
        <% if link.read %>
          <div class="read">
            <%= link_to "Mark as Unread", '#' %>
          </div>
        <% else %>
        <div class="unread">
          <%= link_to "Mark as Read", '#' %>
        </div>
        <% end %>
        <%= link_to "Edit", edit_link_path(link.id) %>
      </div>
    </li>
    <% end %>
  <% end %>
</ul>
</div>

app/views/links/show.html.erb
<%= @link.title %>
<%= @link.url %>
Read: <%= @link.read %>
<%= link_to "Edit link", edit_link_path(@link) %>
<%= link_to "All links", links_path %>

app/views/shared/_errors.html.erb
<% if target.errors.any? %>
  <h4> <%=  pluralize(target.errors.count, "error") %> prohibited this record from being saved: </h4>
  <ul>
    <% target.errors.full_messages.each do |message| %>
      <li><strong class="error"> <%= message %> </strong> </li>
    <% end %>
  </ul>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user, url: { action: "create"} do |f| %>
  <%= render partial: "shared/errors", locals: { target: @user } %>

  <div>
      <%= f.label :email %>
      <%= f.text_field :email, required: true %>
      <br>
      <%= f.label :password %>
      <%= f.password_field :password, required: true %>
      <br>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, required: true %>
      <br>
      <%= f.submit "Create Account" %>
  </div>
<% end %>

app/views/users/new.html.erb
<h2>Create a New Account</h2>
<br><br>
<%= render partial: "form" %>